apiVersion: v1
kind: Pod
metadata:
  name: thread-art-server
spec:
  containers:
    - name: receive
      image: receive
      volumeMounts:
        - mountPath: /thread-art-vol
          name: thread-art-vol
    - name: act
      image: act
      volumeMounts:
        - mountPath: /thread-art-vol
          name: thread-art-vol
    - name: redis
      image: redis:alpine
    - name: server
      image: caddy:2.6
      ports:
        - containerPort: 80
          hostPort: 1025
      volumeMounts:
        - mountPath: /etc/caddy/Caddyfile
          name: caddyfile
        - mountPath: /srv
          name: frontend
        - mountPath: /data
          name: caddy_data
        - mountPath: /config
          name: caddy_config
  volumes:
    - name: thread-art-vol
      persistentVolumeClaim:
        claimName: thread-art-volume
    - name: caddyfile
      hostPath:
        path: ./Caddyfile
        type: File
    - name: frontend
      hostPath:
          path: ./frontend
          type: Directory
    - name: caddy_data
      persistentVolumeClaim:
          claimName: caddy_data
    - name: caddy_config
      persistentVolumeClaim:
          claimName: caddy_config
